org: mingyun
app: bu-up
service: bu-up-sls

frameworkVersion: '2'

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  tableName: 'users-table-${self:provider.stage}'
  jobPosting: 'job-posting-${self:provider.stage}'
  # serverless-offline:
  #   httpsProtocol: "dev"
  #   httpPort: 4000
  #   stageVariables:
  #     foo: "bar"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev-2
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
            - Fn::GetAtt: [ JobPostingTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}
    JOBPOSTING_TABLE: ${self:custom.jobPosting}

functions:
  api:
    handler: lambdas/handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
    JobPostingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - AttributeName: postId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.jobPosting}